package de.srh.view;

import de.srh.dao.impl.UserDAOImpl;
import de.srh.model.User;
import de.srh.service.PasswordService;

import javax.swing.*;
import java.sql.SQLException;

/**
 *
 * @author shiva
 */
public class LoginForm extends JFrame {

    private Object JOptionPane;
    private static User loginUser = null;

    /**
     * Creates new form Login_form
     */
    public LoginForm() {
        initComponents();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        Login_panel = new javax.swing.JPanel();
        Login_heading = new javax.swing.JLabel();
        Username_heading = new javax.swing.JLabel();
        UsernameField1 = new javax.swing.JTextField();
        Password_heading = new javax.swing.JLabel();
        Login_submit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Pwd = new javax.swing.JPasswordField();
        check = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        AppIcon = new javax.swing.JLabel();
        Appname1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 153));

        Login_panel.setBackground(new java.awt.Color(216, 181, 224));
        Login_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Login_heading.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Login_heading.setText("Login");

        Username_heading.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Username_heading.setText("Username:");

        UsernameField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameField1ActionPerformed(evt);
            }
        });

        Password_heading.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Password_heading.setText("Password:");

        Login_submit.setBackground(new java.awt.Color(204, 204, 255));
        Login_submit.setText("Submit");
        Login_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_submitActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setText("Create an Account?");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Pwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PwdActionPerformed(evt);
            }
        });

        check.setBackground(new java.awt.Color(204, 204, 255));
        check.setText("Show Password");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setText("Homepage");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Login_panelLayout = new javax.swing.GroupLayout(Login_panel);
        Login_panel.setLayout(Login_panelLayout);
        Login_panelLayout.setHorizontalGroup(
                Login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Login_panelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(Login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(UsernameField1)
                                        .addComponent(Pwd)
                                        .addGroup(Login_panelLayout.createSequentialGroup()
                                                .addGroup(Login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(Password_heading, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(Login_heading, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(Username_heading, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(Login_panelLayout.createSequentialGroup()
                                                                .addComponent(Login_submit)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 255, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Login_panelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))
        );
        Login_panelLayout.setVerticalGroup(
                Login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Login_panelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Login_heading, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Username_heading)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UsernameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Password_heading)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(Login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Login_submit)
                                        .addComponent(check))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)
                                .addContainerGap(86, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(51, 255, 51));
        jLabel1.setPreferredSize(new java.awt.Dimension(1920, 1080));

        AppIcon.setIcon(new javax.swing.ImageIcon("D:\\Medical management system\\icon.png")); // NOI18N
        AppIcon.setText("jLabel4");
        AppIcon.setPreferredSize(new java.awt.Dimension(40, 40));

        Appname1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Appname1.setForeground(new java.awt.Color(102, 0, 102));
        Appname1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Appname1.setText("MediCare Hospital");
        Appname1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(AppIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Appname1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1901, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(538, 538, 538)
                                                .addComponent(Login_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(AppIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Appname1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Login_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(267, 267, 267))
        );

        pack();
    }// </editor-fold>

    private void Login_submitActionPerformed(java.awt.event.ActionEvent evt) {
        //first get username and password
        String userName= UsernameField1.getText();
        String PassWord= Pwd.getText();

        //Input  validation
        //Case1: if both username and password are blank
        if(userName.equals("")&&PassWord.equals("")){
            javax.swing.JOptionPane.showMessageDialog(this, "Please Enter Username and Password");
        }
        if(!(userName.equals(""))&&PassWord.equals("")){
            javax.swing.JOptionPane.showMessageDialog(this, "Please Enter Password");
        }
        if(userName.equals("")&&!(PassWord.equals(""))){
            javax.swing.JOptionPane.showMessageDialog(this, "Please Enter username");
        }

        validateCredentials(userName, PassWord);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        this.toBack();
        this.setVisible(false);
        RegistrationForm registrationForm = new RegistrationForm();
        registrationForm.setVisible(true);
        registrationForm.toFront();
        registrationForm.setLocationRelativeTo(null);

    }

    private void UsernameField1ActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void PwdActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {
        if(check.isSelected()){
            Pwd.setEchoChar((char)0);
        }else{
            Pwd.setEchoChar('*');
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        this.toBack();
        this.setVisible(false);
        Homepage homepage = new Homepage();
        homepage.toFront();
        homepage.setVisible(true);
        homepage.setLocationRelativeTo(null);
        homepage.setState(java.awt.Frame.NORMAL);

    }

        /**
         * validates Login Credentials and grants access if passed
         * @author Andreas Lakus
         * @param username
         * @param password
         */
        private boolean validateCredentials(String username, String password){

            UserDAOImpl userDAO = new UserDAOImpl();
            try {
                loginUser = userDAO.findUserByUserName(username);
            } catch (SQLException ex) {
                throw new RuntimeException(ex);
            }
            if (loginUser == null){
                String msg = username + " is not a registered User";
                javax.swing.JOptionPane.showMessageDialog(this, msg);
                return false;
            }

            try {
                if(!userDAO.getUserActivationStatus(loginUser.getId())){
                    javax.swing.JOptionPane.showMessageDialog(this, "Your Account must be activated by an Admin");
                    return false;
                }
            } catch (SQLException e) {
                throw new RuntimeException(e);
            }

            PasswordService passwordService = new PasswordService();
            // TODO (AL) count login failures and deactivate account if limit reached -> reactivate Admin
            if (passwordService.verifyPasswordWithHash(loginUser.getPassword().toString(), password)){
                try {
                    loadViewByUserRole(loginUser.getId());
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Password false");
                return false;
            }
            return true;
        }

    /**
     * Loads Main Menu by Users Role
     * @author Andreas Lakus
     * @param id
     * @throws SQLException
     */
    private void loadViewByUserRole(int id) throws SQLException {
        UserDAOImpl userDAO = new UserDAOImpl();
        switch(userDAO.getUserRole(id)){
            case "user":
                javax.swing.JOptionPane.showMessageDialog(this, "User");
                break;
            case "admin":
                this.toBack();
                this.setVisible(false);
                AdminHome adminHome = new AdminHome();
                adminHome.toFront();
                adminHome.setLocationRelativeTo(null);
                adminHome.setState(java.awt.Frame.NORMAL);
                adminHome.setVisible(true);
                break;
            case "nurse":
                javax.swing.JOptionPane.showMessageDialog(this, "nurse");
                break;
            case "doctor":
                javax.swing.JOptionPane.showMessageDialog(this, "Doctor");
                break;
            default:
                javax.swing.JOptionPane.showMessageDialog(this, "You dont have a permission role, contact admin");

        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify
    private javax.swing.JLabel AppIcon;
    private javax.swing.JLabel Appname1;
    private javax.swing.JLabel Login_heading;
    private javax.swing.JPanel Login_panel;
    private javax.swing.JButton Login_submit;
    private javax.swing.JLabel Password_heading;
    private javax.swing.JPasswordField Pwd;
    private javax.swing.JTextField UsernameField1;
    private javax.swing.JLabel Username_heading;
    private javax.swing.JCheckBox check;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration
}